# Generated by Django 6.0.6 on 2026-06-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='operacao',
            field=models.CharField(choices=[('INSERT', 'Inserção'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('SELECT', 'Leitura')], max_length=10),
        ),
    ]
