# Generated by Django 6.0.6 on 2026-06-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_convenio_paciente_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='anonimizado',
            field=models.BooleanField(default=False, verbose_name='Dados anonimizados'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do consentimento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimento_lgpd',
            field=models.BooleanField(default=False, verbose_name='Consentimento LGPD'),
        ),
    ]
