# Generated by Django 6.0.6 on 2026-06-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_atendimento_mapa_dor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('especialidade', models.CharField(blank=True, max_length=100, verbose_name='Especialidade')),
                ('campos_extras', models.JSONField(blank=True, default=list, help_text='Lista de campos extras ex: [{"label":"Pressão Arterial","tipo":"text"}]', verbose_name='Campos do template')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Consulta',
                'verbose_name_plural': 'Tipos de Consulta',
                'db_table': 'tipo_consulta',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados do Template Clínico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Final (R$)'),
        ),
        migrations.CreateModel(
            name='TabelaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Base (R$)')),
                ('tipo_consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_valor', to='consultas.tipoconsulta', verbose_name='Tipo de Consulta')),
            ],
            options={
                'verbose_name': 'Tabela de Valor',
                'verbose_name_plural': 'Tabela de Valores',
                'db_table': 'tabela_valor',
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.tipoconsulta', verbose_name='Tipo de Consulta'),
        ),
    ]
