# Generated by Django 6.0.6 on 2026-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0004_tipoconsulta_consulta_dados_extras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateEspecialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Geriatria', 'Geriatria'), ('Ginecologia', 'Ginecologia'), ('Neurologia', 'Neurologia'), ('Oftalmologia', 'Oftalmologia'), ('Oncologia', 'Oncologia'), ('Ortopedia', 'Ortopedia'), ('Otorrinolaringologia', 'Otorrinolaringologia'), ('Pediatria', 'Pediatria'), ('Psiquiatria', 'Psiquiatria'), ('Reumatologia', 'Reumatologia'), ('Urologia', 'Urologia'), ('Clínica Geral', 'Clínica Geral')], max_length=100, unique=True, verbose_name='Especialidade')),
                ('campos_extras', models.JSONField(blank=True, default=list, verbose_name='Campos do prontuário')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Template por Especialidade',
                'verbose_name_plural': 'Templates por Especialidade',
                'db_table': 'template_especialidade',
                'ordering': ['especialidade'],
            },
        ),
    ]
