# Generated by Django 5.2.1 on 2026-05-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(choices=[('Cardiologia', 'Cardiologia'), ('Dermatologia', 'Dermatologia'), ('Endocrinologia', 'Endocrinologia'), ('Gastroenterologia', 'Gastroenterologia'), ('Geriatria', 'Geriatria'), ('Ginecologia', 'Ginecologia'), ('Neurologia', 'Neurologia'), ('Oftalmologia', 'Oftalmologia'), ('Oncologia', 'Oncologia'), ('Ortopedia', 'Ortopedia'), ('Otorrinolaringologia', 'Otorrinolaringologia'), ('Pediatria', 'Pediatria'), ('Psiquiatria', 'Psiquiatria'), ('Reumatologia', 'Reumatologia'), ('Urologia', 'Urologia'), ('Clínica Geral', 'Clínica Geral')], max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicos/')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
                'ordering': ['especialidade', 'usuario__first_name'],
            },
        ),
    ]
